spring:
  application:
    name: Ums

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/usermanagementsystem?useSSL=false
    username: root
    password: root1234
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: false
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/