spring:
  application:
    name: subscriber-service

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tweetDB?useSSL=false
    username: root
    password: root1234!
    testWhileIdle: true
    validationQuery: SELECT 1

  jpa:
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: update

server:
  port: 8080
